hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
indent_style = "Block"

reorder_imports = false
reorder_modules = false
imports_indent = "Block"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"

blank_lines_upper_bound = 2

use_small_heuristics = "Off"
combine_control_expr = false
control_brace_style = "AlwaysSameLine"
brace_style = "SameLineWhere"
wrap_comments = false
condense_wildcard_suffixes = false
empty_item_single_line = true
fn_params_layout = "Tall"
fn_single_line = false
format_code_in_doc_comments = false
format_strings = false
hex_literal_case = "Upper"
match_arm_blocks = false
match_arm_indent = true
match_arm_leading_pipes = "Preserve"
match_block_trailing_comma = true
format_macro_matchers = false
normalize_doc_attributes = true
overflow_delimited_expr = false
reorder_impl_items = true
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_lit_single_line = false

# for now I want the formatter disabled, I'll re-enable it in the 
# future with some of the configs I set above as I learn more about 
# it and can trust it.
disable_all_formatting = true