[package]
name = "roseate-core"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
rayon = "1.11.0"
imagesize = "0.14.0" # zero deps is crazy
svg_metadata = "0.5.1"
kamadak-exif = "0.6.1"

# decoder backends
image = {version = "0.25.9", features = ["rayon", "png", "jpeg", "gif", "webp", "tiff"], default-features = false}
zune-image = {version = "0.4.15", features = ["threads", "simd", "metadata", "png", "jpeg", "jpeg-xl"], default-features = false}

[dev-dependencies]
env_logger = "0.11"
